[package]
name = "mcli"
version = "0.1.0"
authors = ["Xiuming Lee <lxmcoder@163.com>"]
description = "A command-line tool."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
